[tool.poetry]
description = ""
name = "IMDDiscordBot"
version = "0.1.0"
authors = ["NEDuck <cj96cj9696cj@gmail.com>"]

[tool.poetry.dependencies]
Flask = "^2.0.1"
discord = "^1.7.3"
discord-py-slash-command = "^2.4.1"
python = "^3.8"
python-dotenv = "^0.19.0"
replit = "^3.2.4"